version: 2
jobs:
  test:
    docker:
      - image: registry.dev.brainhub.pl/tools/rancher-circleci
        auth:
          username: $HARBOR_USER
          password: $HARBOR_PASSWORD
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u $HARBOR_USER -p $HARBOR_PASSWORD registry.dev.brainhub.pl
      - run: docker build --build-arg NODE_ENV=development -t react-carousel .
      - run: docker run --rm --name react-carousel --entrypoint '/bin/sh' react-carousel -c 'npm run lint'
      - run: docker run --rm --name react-carousel --entrypoint '/bin/sh' react-carousel -c 'npm run test-unit'

  publish_package:
    docker:
      - image: circleci/node:8.16
    steps:
      - checkout
      - run:
          name: npm install
          command: npm install
      - run:
          name: npm build
          command: npm run build
      - run:
          name: npm publish
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
            npm publish
      - run:
          name: publish gh pages
          command: ./tools/deploy-gh-pages.sh

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - publish_package:
          requires:
            - test
          filters:
            branches:
              only:
                - master
